name: Deploy node
on:
  push:
    branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Deploy on cloud
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: 210.79.128.114
            username: ubuntu
            key: ${{ secrets.PRIVATE_KEY }}
            script: |
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
              cd /home/ubuntu/server/devops-test
              git pull
              pnpm install
              pm2 restart 0
          